packages:
  - "docs"
  - "packages/**"
  - "!**/__tests__/**"

catalog:
  # cosmiconfig > 8.2.0 will lead bundle size to 10MB +
  "cosmiconfig": "8.2.0"

catalogs:
  # As adapter cz-git needs keep with commitizen's inquirer (https://github.com/commitizen/cz-cli) same version
  inquirer:
    "@types/inquirer": "8.2.5"
    "inquirer": "8.2.5"

  # rimraf v4 requires node >= v14
  rimraf:
    "@types/rimraf": "3.0.2"
    "rimraf": "3.0.2"

  commitlint:
    # @qbbsh/config-validator is a fork of @commitlint/config-validator for bundle build (https://github.com/qbbsh/config-validator)
    "@commitlint/config-validator": "npm:@qbbsh/config-validator@19.5.0"
    "@commitlint/cli": "^19.5.0"
    "@commitlint/config-conventional": "^19.5.0"
    "@commitlint/resolve-extends": "^19.5.0"
    "@commitlint/types": "^19.5.0"
