// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Badge: typeof import('./theme/components/Badge.vue')['default']
    CodeGroupItem: typeof import('./theme/components/CodeGroupItem.vue')['default']
    HomePage: typeof import('./theme/components/HomePage.vue')['default']
  }
}
